spring.application.name=PaymentGateway
#server.port=8082

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${GATEWAY_DB_URL}
#spring.datasource.url=jdbc:postgresql://localhost:5433/gateway
spring.datasource.username=${GATEWAY_DB_USERNAME}
#spring.datasource.username=parsa
spring.datasource.password=${GATEWAY_DB_PASSWORD}
#spring.datasource.password=123

wallets.gateway.username=gateway
wallets.gateway.password=12345
wallets.base.url=${WALLETS_BASE_URL}
#wallets.base.url=http://localhost:8081

ftp.host=${FTP_HOST}
ftp.user=${FTP_USER}
ftp.password=${FTP_PASSWORD}

cron.successful=15 * * * * *
cron.unsuccessful=30 * * * * *
cron.pending=45 * * * * *